import { Kategori, Usaha } from './types';

export const categories: Kategori[] = [
  { id: '1', nama_kategori: 'Warung Makan', icon: 'utensils', created_at: '' },
  { id: '2', nama_kategori: 'Restoran', icon: 'utensils-crossed', created_at: '' },
  { id: '3', nama_kategori: 'Cafe', icon: 'coffee', created_at: '' },
  { id: '4', nama_kategori: 'Snack & Keripik', icon: 'cookie', created_at: '' },
  { id: '5', nama_kategori: 'Rumah Busana', icon: 'shirt', created_at: '' },
  { id: '6', nama_kategori: 'Toko Komputer', icon: 'monitor', created_at: '' },
  { id: '7', nama_kategori: 'Toko Elektronik', icon: 'smartphone', created_at: '' },
  { id: '8', nama_kategori: 'Toko Aksesoris', icon: 'gem', created_at: '' },
  { id: '9', nama_kategori: 'Toko Ikan Hias', icon: 'fish', created_at: '' },
  { id: '10', nama_kategori: 'Bengkel', icon: 'wrench', created_at: '' },
  { id: '11', nama_kategori: 'Salon', icon: 'scissors', created_at: '' },
  { id: '12', nama_kategori: 'Percetakan', icon: 'printer', created_at: '' },
  { id: '13', nama_kategori: 'Apotek', icon: 'pill', created_at: '' },
  { id: '14', nama_kategori: 'UMKM Produk Lokal', icon: 'package', created_at: '' },
];

export const kecamatanList = [
  'Singkawang Barat',
  'Singkawang Timur',
  'Singkawang Utara',
  'Singkawang Selatan',
  'Singkawang Tengah',
];

export const kelurahanList: Record<string, string[]> = {
  'Singkawang Barat': ['Tengah', 'Melayu', 'Pasiran', 'Sedanau'],
  'Singkawang Timur': ['Bukit Batu', 'Darat Sebingkai', 'Naram', 'Sungaibeliung'],
  'Singkawang Utara': ['Lasembak', 'Lembah', 'Roban', 'Sengkalo'],
  'Singkawang Selatan': ['Bagak Sahwa', 'Pangmilang', 'Sijang', 'Sungai Secopong'],
  'Singkawang Tengah': ['Jawa', 'Kumbang', 'Muliabaru', 'Nyiur Dalam'],
};

export const businesses: Usaha[] = [
  {
    id: '1',
    user_id: 'user1',
    kategori_id: '1',
    nama_usaha: 'Warung Makan Pak Budi',
    deskripsi: 'Warung makan khas Singkawang dengan menu tradisional seperti bubur pedas, lakse, dan mi kering. Buka dari pagi hingga sore. Tersedia also menu seafood segar.',
    alamat: 'Jl. Diponegoro No. 45',
    kecamatan: 'Singkawang Barat',
    kelurahan: 'Tengah',
    telepon: '0562-123456',
    foto: 'https://images.pexels.com/photos/67468/pexels-photo-67468.jpeg?auto=compress&cs=tinysrgb&w=600',
    latitude: 0.9092,
    longitude: 108.9843,
    status: 'approved',
    created_at: new Date().toISOString(),
    kategori: categories[0],
  },
  {
    id: '2',
    user_id: 'user2',
    kategori_id: '3',
    nama_usaha: 'Kopi Kita Cafe',
    deskripsi: 'Cafe modern dengan suasana nyaman untuk bersantai. Menyediakan berbagai varian kopi lokal dan internasional, serta kue dan pastry segar.',
    alamat: 'Jl. Letjen Sutoyo No. 12',
    kecamatan: 'Singkawang Tengah',
    kelurahan: 'Jawa',
    telepon: '0562-234567',
    foto: 'https://images.pexels.com/photos/1855152/pexels-photo-1855152.jpeg?auto=compress&cs=tinysrgb&w=600',
    latitude: 0.9101,
    longitude: 108.9856,
    status: 'approved',
    created_at: new Date().toISOString(),
    kategori: categories[2],
  },
  {
    id: '3',
    user_id: 'user3',
    kategori_id: '2',
    nama_usaha: 'Restoran Seafood Bahari',
    deskripsi: 'Restoran seafood terlengkap di Singkawang. Menyajikan hidangan laut segar dengan bumbu khas. Kapasitas 200 orang, cocok untuk acara keluarga.',
    alamat: 'Jl. Pahlawan No. 88',
    kecamatan: 'Singkawang Timur',
    kelurahan: 'Bukit Batu',
    telepon: '0562-345678',
    foto: 'https://images.pexels.com/photos/96085/pexels-photo-96085.jpeg?auto=compress&cs=tinysrgb&w=600',
    latitude: 0.9156,
    longitude: 108.9901,
    status: 'approved',
    created_at: new Date().toISOString(),
    kategori: categories[1],
  },
  {
    id: '4',
    user_id: 'user4',
    kategori_id: '4',
    nama_usaha: 'Keripik Bu Tini',
    deskripsi: 'Produsen keripik pisang, ubi, dan singkong khas Singkawang. Tersedia berbagai varian rasa. Menerima pesanan dalam jumlah besar untuk oleh-oleh.',
    alamat: 'Jl. Mangga No. 23',
    kecamatan: 'Singkawang Selatan',
    kelurahan: 'Bagak Sahwa',
    telepon: '0562-456789',
    foto: 'https://images.pexels.com/photos/5928/pexels-photo-5928.jpeg?auto=compress&cs=tinysrgb&w=600',
    latitude: 0.9045,
    longitude: 108.9812,
    status: 'approved',
    created_at: new Date().toISOString(),
    kategori: categories[3],
  },
  {
    id: '5',
    user_id: 'user5',
    kategori_id: '5',
    nama_usaha: 'Butik Surya Fashion',
    deskripsi: 'Rumah busana dengan koleksi pakaian pria dan wanita modern tradisional. Menerima jahit pesan baju adat, gaun pesta, dan pakaian sehari-hari.',
    alamat: 'Jl. Hasan Basri No. 56',
    kecamatan: 'Singkawang Tengah',
    kelurahan: 'Nyiur Dalam',
    telepon: '0562-567890',
    foto: 'https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg?auto=compress&cs=tinysrgb&w=600',
    latitude: 0.9098,
    longitude: 108.9878,
    status: 'approved',
    created_at: new Date().toISOString(),
    kategori: categories[4],
  },
  {
    id: '6',
    user_id: 'user6',
    kategori_id: '6',
    nama_usaha: 'Techno Komputer',
    deskripsi: 'Menyediakan komputer, laptop, dan aksesoris komputer dengan berbagai merek. Jasa servis dan perbaikan komputer. Garansi resmi tersedia.',
    alamat: 'Jl. Ahmad Yani No. 78',
    kecamatan: 'Singkawang Barat',
    kelurahan: 'Melayu',
    telepon: '0562-678901',
    foto: 'https://images.pexels.com/photos/1714208/pexels-photo-1714208.jpeg?auto=compress&cs=tinysrgb&w=600',
    latitude: 0.9078,
    longitude: 108.9834,
    status: 'approved',
    created_at: new Date().toISOString(),
    kategori: categories[5],
  },
  {
    id: '7',
    user_id: 'user7',
    kategori_id: '7',
    nama_usaha: 'Elektronik Jaya',
    deskripsi: 'Toko elektronik lengkap dengan TV, kulkas, AC, dan peralatan rumah tangga. Harga kompetitif dengan layanan after-sales terpercaya.',
    alamat: 'Jl. Imam Bonjol No. 34',
    kecamatan: 'Singkawang Timur',
    kelurahan: 'Naram',
    telepon: '0562-789012',
    foto: 'https://images.pexels.com/photos/39304/microwave-electronics-product-39304.jpeg?auto=compress&cs=tinysrgb&w=600',
    latitude: 0.9145,
    longitude: 108.9922,
    status: 'approved',
    created_at: new Date().toISOString(),
    kategori: categories[6],
  },
  {
    id: '8',
    user_id: 'user8',
    kategori_id: '8',
    nama_usaha: 'Gallery Aksesoris',
    deskripsi: 'Toko aksesoris fashion dengan koleksi terbaru. Gelang, kalung, anting, dan berbagai aksesoris wanita lainnya dengan harga terjangkau.',
    alamat: 'Jl. Sudirman No. 67',
    kecamatan: 'Singkawang Utara',
    kelurahan: 'Lasembak',
    telepon: '0562-890123',
    foto: 'https://images.pexels.com/photos/19090/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600',
    latitude: 0.9189,
    longitude: 108.9789,
    status: 'approved',
    created_at: new Date().toISOString(),
    kategori: categories[7],
  },
  {
    id: '9',
    user_id: 'user9',
    kategori_id: '9',
    nama_usaha: 'Toko Ikan Hias Mawar',
    deskripsi: 'Spesialis ikan hias air tawar dan laut. Menyediakan aquarium, pakan ikan, dan perlengkapan aquarium lengkap. Konsultasi gratis.',
    alamat: 'Jl. Bunga No. 12',
    kecamatan: 'Singkawang Selatan',
    kelurahan: 'Pangmilang',
    telepon: '0562-901234',
    foto: 'https://images.pexels.com/photos/118591/pexels-photo-118591.jpeg?auto=compress&cs=tinysrgb&w=600',
    latitude: 0.9067,
    longitude: 108.9801,
    status: 'approved',
    created_at: new Date().toISOString(),
    kategori: categories[8],
  },
  {
    id: '10',
    user_id: 'user10',
    kategori_id: '10',
    nama_usaha: 'Bengkel Motor Pak Dian',
    deskripsi: 'Bengkel motor dengan mekanik berpengalaman. Melayani servis berkala, perbaikan mesin, dan modifikasi motor. Tersedia juga spare part.',
    alamat: 'Jl. Garuda No. 45',
    kecamatan: 'Singkawang Timur',
    kelurahan: 'Darat Sebingkai',
    telepon: '0562-012345',
    foto: 'https://images.pexels.com/photos/1906235/pexels-photo-1906235.jpeg?auto=compress&cs=tinysrgb&w=600',
    latitude: 0.9167,
    longitude: 108.9889,
    status: 'approved',
    created_at: new Date().toISOString(),
    kategori: categories[9],
  },
  {
    id: '11',
    user_id: 'user11',
    kategori_id: '11',
    nama_usaha: 'Salon Cantik',
    deskripsi: 'Salon kecantikan dengan layanan potong rambut, facial, manicure, pedicure, dan treatment rambut. Dijalankan oleh stylists profesional.',
    alamat: 'Jl. Melati No. 89',
    kecamatan: 'Singkawang Tengah',
    kelurahan: 'Kumbang',
    telepon: '0562-111222',
    foto: 'https://images.pexels.com/photos/3993316/pexels-photo-3993316.jpeg?auto=compress&cs=tinysrgb&w=600',
    latitude: 0.9112,
    longitude: 108.9867,
    status: 'approved',
    created_at: new Date().toISOString(),
    kategori: categories[10],
  },
  {
    id: '12',
    user_id: 'user12',
    kategori_id: '12',
    nama_usaha: 'Percetakan Sentral',
    deskripsi: 'Percetakan digital dan offset. Melayani cetak brosur, kartu nama, spanduk, poster, dan undangan. Harga bersaing, hasil berkualitas.',
    alamat: 'Jl. Kenanga No. 33',
    kecamatan: 'Singkawang Barat',
    kelurahan: 'Sedanau',
    telepon: '0562-222333',
    foto: 'https://images.pexels.com/photos/258528/pexels-photo-258528.jpeg?auto=compress&cs=tinysrgb&w=600',
    latitude: 0.9089,
    longitude: 108.9811,
    status: 'approved',
    created_at: new Date().toISOString(),
    kategori: categories[11],
  },
  {
    id: '13',
    user_id: 'user13',
    kategori_id: '13',
    nama_usaha: 'Apotek Sehat Selalu',
    deskripsi: 'Apotek dengan obat-obatan lengkap dan alat kesehatan. Apoteker berlisensi siap memberikan konsultasi. Melayani BPJS dan resep dokter.',
    alamat: 'Jl. Anggrek No. 56',
    kecamatan: 'Singkawang Utara',
    kelurahan: 'Lembah',
    telepon: '0562-333444',
    foto: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=600',
    latitude: 0.9178,
    longitude: 108.9767,
    status: 'approved',
    created_at: new Date().toISOString(),
    kategori: categories[12],
  },
  {
    id: '14',
    user_id: 'user14',
    kategori_id: '14',
    nama_usaha: 'UMKM Kerajinan Rotan',
    deskripsi: 'Pengrajin rotan lokal dengan produk berkualitas. Membuat kursi, meja, tikar, dan anyaman rotan untuk furniture dan dekorasi.',
    alamat: 'Jl. Rotan No. 21',
    kecamatan: 'Singkawang Selatan',
    kelurahan: 'Sijang',
    telepon: '0562-444555',
    foto: 'https://images.pexels.com/photos/929192/pexels-photo-929192.jpeg?auto=compress&cs=tinysrgb&w=600',
    latitude: 0.9056,
    longitude: 108.9789,
    status: 'approved',
    created_at: new Date().toISOString(),
    kategori: categories[13],
  },
  {
    id: '15',
    user_id: 'user15',
    kategori_id: '1',
    nama_usaha: 'Bubur Pedas Makmur',
    deskripsi: 'Gerai bubur pedas legendaris sejak 1980. Rekomendasi warga lokal untuk sarapan tradisional. Tersedia take away dan delivery.',
    alamat: 'Jl. Pemuda No. 10',
    kecamatan: 'Singkawang Barat',
    kelurahan: 'Pasiran',
    telepon: '0562-555666',
    foto: 'https://images.pexels.com/photos/769289/pexels-photo-769289.jpeg?auto=compress&cs=tinysrgb&w=600',
    latitude: 0.9067,
    longitude: 108.9823,
    status: 'approved',
    created_at: new Date().toISOString(),
    kategori: categories[0],
  },
  {
    id: '16',
    user_id: 'user16',
    kategori_id: '3',
    nama_usaha: 'Roti Bakar SD',
    deskripsi: 'Gerai roti bakar legendaris dengan berbagai topping. Tersedia juga susu segar dan minuman lainnya. Tempat nongkrong favorit remaja.',
    alamat: 'Jl. Veteran No. 78',
    kecamatan: 'Singkawang Tengah',
    kelurahan: 'Muliabaru',
    telepon: '0562-666777',
    foto: 'https://images.pexels.com/photos/2233348/pexels-photo-2233348.jpeg?auto=compress&cs=tinysrgb&w=600',
    latitude: 0.9109,
    longitude: 108.9845,
    status: 'approved',
    created_at: new Date().toISOString(),
    kategori: categories[2],
  },
];
